source 'https://rubygems.org'

gem 'foreman'
gem 'mongoid','~> 2.7'
gem 'bson_ext'
gem 'rack'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'json'
gem 'haml'
gem 'sass'
gem 'args_parser'
gem 'nokogiri'
gem 'curb'
gem 'mini_exiftool'
gem 'sys-filesystem'
