# mongo db config
mongo :
  host: '127.0.0.1'
  port: 27017
  database : 'videom'

video_dir : 'videos'
thumb_dir : 'thumbs'
disk : '/'
retry : 3
per_page : 40

tags : 
     - 'tag1'
     - 'tag2'
crawl_page : 3
